### ISSUE TITLE
Frontend Setup

### ISSUE THREAD

**Issue by kokchuan-kc** [kokchuan-kc/WraithTech-v2#2]
Setup convenient development environment such as hot reload, bundler and npm scripts

**Comment by casey-kc-kokchuan** [comment]
#2dta22

**Comment by casey-kc-kokchuan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Setup frontend environment](https://trello.com/c/ukSOAB9R/2-setup-frontend-environment)

**Comment by caseyhkc** [comment]
## Summary

#### Progress so far:
1. Initial setup of webpack, npm
2. File structure
3. Bundling angular modules

#### TODO: 
1. Load html template for directives/components
2. Setup webpack-dev-server (to utilise live reload/hmr)
